version: '3.8'
# Make sure to place this file outside of the api project folder.
# Both projects folder should be at the same level.
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: thingy-api-orange/environments/postgres.env
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./thingy-api-orange/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command: "start-dev"
    restart: always
    env_file: thingy-api-orange/environments/keycloak.env
    volumes:
      - ./thingy-api-orange/keycloak_theme/thingy:/opt/keycloak/themes/thingy
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - backend
      - web
  
  influxdb:
    image: influxdb:2.7-alpine
    restart: always
    env_file: thingy-api-orange/environments/influx.env
    volumes:
      - influx-data:/var/lib/influxdb2
    ports:
      - 8086:8086
    networks:
      - backend
      - web

  thingy_api:
    build:
      context: ./thingy-api-orange
      dockerfile: Dockerfile
    restart: always
    env_file: thingy-api-orange/environments/api.env
    volumes:
      - ./thingy-api-orange/data:/data
      - ./thingy-api-orange/logs:/logs
    depends_on:
      - postgres
      - keycloak
    ports:
      - 8000:8000
    networks:
      - backend
      - web

  frontend:
    build:
      context: ./thingy-client-orange/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - backend
      - web
    env_file:
      - "./thingy-client-orange/.env"

networks:
  backend:
  web:
    external: true

volumes:
  pg-data:
  influx-data:
