version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: environments/postgres.env
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    networks:
      - keycloak-network
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command: "start-dev"
    restart: always
    env_file: environments/keycloak.env
    volumes:
      - ./keycloak_theme/thingy:/opt/keycloak/themes/thingy
    ports:
      - "8888:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network
  
  influxdb:
    image: influxdb:2.7-alpine
    restart: always
    env_file: environments/influx.env
    volumes:
      - influx-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - backend

  thingy_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: environments/api.env
    volumes:
      - ./data:/data
      - ./logs:/logs
    depends_on:
      - postgres
      - keycloak
    ports:
      - "8000:8000"
    networks:
      - backend
      - keycloak-network
    

networks:
  keycloak-network:
    driver: bridge
  backend:

volumes:
  pg-data:
  influx-data:
